telegram.bot:
    token: ENC(F/JNx8p9TSNvlgsVKy2rwE4sKNJAslhtPxfKmaWR0J46bZZu7umlIAWo13X4xfwiGC5OL3HtU6s=)
    username: super_green_schedule_bot

feign.client.config:
  default:
    loggerLevel: full
    errorDecoder: com.anloboda.schedule.api.decoder.ItalkiApiErrorDecoder
  italki:
    url: https://api.italki.com/
    get-schedule:
      cache:
        maxSize: 1
        expireAfterWrite: 60

resilience4j:
  circuitbreaker:
    instances:
      get-schedule:
        failure-rate-threshold: 5
        minimum-number-of-calls: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
        record-exceptions:
          - com.anloboda.schedule.api.ItalkiApiErrorException