telegram.bot:
    token: ENC(F/JNx8p9TSNvlgsVKy2rwE4sKNJAslhtPxfKmaWR0J46bZZu7umlIAWo13X4xfwiGC5OL3HtU6s=)
    username: super_green_schedule_bot

feign.client.config:
  default:
    loggerLevel: full
  italki:
    url: https://api.italki.com/
    schedule:
      cache:
        maxSize: 1
        expireAfterWrite: 60