# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build and test
      run: |
        ./gradlew build --console=plain --no-daemon > output.txt
        echo "::set-output name=test-output::$(cat output.txt)"

    - name: Upload test output artifact
      uses: actions/upload-artifact@v2
      with:
        name: test-output
        path: output.txt

    - name: Publish test results
      if: always()
      uses: dorny/test-results-parser@v1
      with:
      files: test-results/**/*.xml